Repository ZTX-Foundation/tuxedo, pull requests merged in 2023-10, with the labels that each got.

#42 fix: Broken Integration Test
  .env.example
  .github/workflows/tests.yml
  README.md
  proposals/Addresses.sol
  test/integration/BaseTest.sol
Labels: bug

#43 feat: token deployment
  proposals/Addresses.sol
Labels: enhancement

#44 feat: deployment of ZTX base system
  proposals/Addresses.sol
  proposals/TestProposals.sol
  proposals/zips/zip001.sol
  proposals/zips/zipTest.sol
  script/deploy/DeployProposal.s.sol
Labels: enhancement

#50 fix!: fixes for harvesting
  README.md
  dist/v1.0.0-rc.2/abi/GameConsumer.abi.json
  src/game/GameConsumer.sol
  test/unit/game/GameConsumer.t.sol
Labels: bug, enhancement

#51 chore: updates for the recent token deployment
  README.md
  dist/v1.0.0/abi/Token.abi.json
Labels: documentation

#59 feat: The ZTX Base System proposal for the wearable drop
  doc/ERC1155ADMINMINT.md
  proposals/Addresses.sol
  proposals/TestProposals.sol
  proposals/zips/zip001.sol
  proposals/zips/zip002.sol
  proposals/zips/zipTest.sol
  script/deploy/DeployProposal.s.sol
  src/nfts/ERC1155AdminMinter.sol
  test/integration/nfts/ERC1155AdminMinter.sol
  test/unit/nfts/ERC1155AdminMinter.t.sol
  test/unit/token/Token.t.sol
Labels: enhancement

#64 chore: README and ABI updates
  README.md
  dist/v1.0.1/abi/Core.abi.json
  dist/v1.0.1/abi/CoreRef.abi.json
  dist/v1.0.1/abi/ERC1155AdminMinter.abi.json
  dist/v1.0.1/abi/ERC1155MaxSupplyMintable.abi.json
  dist/v1.0.1/abi/GlobalReentrancyLock.abi.json
  dist/v1.0.1/abi/IGlobalReentrancyLock.abi.json
  dist/v1.0.1/abi/Roles.abi.json
  dist/v1.0.1/abi/Token.abi.json
  proposals/Addresses.sol
Labels: documentation

#57 test: Remove unneeded role additions, use deployed ztx token
  test/integration/nfts/ERC1155AutoGraphMinter.sol
Labels: enhancement
